# Generated by Django 3.0.2 on 2020-01-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('patient_appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.BigIntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=100)),
                ('doctor_id', models.CharField(max_length=100)),
                ('slot_date', models.DateField(max_length=100)),
                ('slot_time', models.TimeField(max_length=100)),
                ('created_at', models.DateField(max_length=100)),
                ('udated_at', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patientID', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='receptionist',
            fields=[
                ('recep_name', models.CharField(max_length=100)),
                ('recep_id', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_id', models.IntegerField(max_length=100)),
            ],
        ),
    ]
