# Generated by Django 2.2.6 on 2020-01-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='patient_phone',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
