# Generated by Django 3.0.3 on 2020-02-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0002_appointments_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone_No', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
