# Generated by Django 3.0.3 on 2020-02-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0003_auto_20200224_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=15)),
                ('first_time_slot_from', models.TimeField()),
                ('first_time_slot_to', models.TimeField()),
                ('second_time_slot_from', models.TimeField()),
                ('second_time_slot_to', models.TimeField()),
                ('third_time_slot_from', models.TimeField()),
                ('third_time_slot_to', models.TimeField()),
            ],
        ),
    ]
