# Generated by Django 3.0.3 on 2020-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0004_dayschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='patient_phone',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
