# Generated by Django 3.0.3 on 2020-02-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0006_auto_20200225_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='slot_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='slot_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='udated_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='hospital_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='recep_id',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
