# Generated by Django 3.0.3 on 2020-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0007_auto_20200225_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='id',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.EmailField(max_length=254),
        ),
    ]
