# Generated by Django 3.0.3 on 2020-02-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0008_auto_20200225_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
