# Generated by Django 3.0.3 on 2020-02-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0009_auto_20200225_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
