# Generated by Django 3.0.3 on 2020-03-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0010_auto_20200229_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='presription',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
