# Generated by Django 3.0.3 on 2020-03-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0011_appointments_presription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='presription',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
