# Generated by Django 3.0.3 on 2020-03-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0012_auto_20200301_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='presription',
            new_name='prescription',
        ),
    ]
