# Generated by Django 3.0.3 on 2020-03-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0013_auto_20200301_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone_No',
            new_name='phone_no',
        ),
    ]
