# Generated by Django 3.0.3 on 2020-03-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0015_auto_20200302_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='patient_phone',
            field=models.BigIntegerField(),
        ),
    ]
