# Generated by Django 3.0.3 on 2020-03-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0017_auto_20200303_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='department_name',
            new_name='department',
        ),
        migrations.AddField(
            model_name='appointments',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
