# Generated by Django 3.0.3 on 2020-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0018_auto_20200303_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='labReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.EmailField(max_length=254)),
                ('reports', models.FileField(upload_to='')),
                ('upload_date', models.DateField()),
                ('upload_time', models.TimeField()),
            ],
        ),
    ]
