# Generated by Django 3.0.3 on 2020-03-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0019_labreports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreports',
            name='reports',
            field=models.FileField(upload_to=None),
        ),
    ]
