# Generated by Django 3.0.3 on 2020-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0020_auto_20200305_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='laboratory',
            fields=[
                ('id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
