# Generated by Django 3.0.3 on 2020-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0021_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
    ]
